### PR TITLE
Newsweek feature

### PR DESCRIPTION
**Pull request by Trodrige**
Work on the Newsweek page clone. This PR includes:

1. Laying out the page sections using Bootstrap Grid (rows and columns) for the various breakpoints.

2. I added the page's components using Bootstrap cards, and jumbotrons.

3. Also, I used Bootstrap col and order classes to make all the sections responsive and reorder accordingly.

You can find a screenshot of the page here: https://raw.githack.com/Trodrige/newsweek-clone/newsweek-feature/index.html

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Really shiny! Great work @Trodrige :medal_military: 
Just one tiny detail to address :smile: Please see below:

#### Descriptive PR
You need a more descriptive PR as it is a hard requirement. Consider describing the work you have completed in the branch in as much detail as you can and even include a link to the live project to speed up your review!
screenshot

#### [OPTIONAL]
You can try adding a really cool screenshot to your readme file. It will increase the shininess of your readme file by a factor of 100000 :laughing: 

### Summary
This is pretty amazing work! Very very responsive :100: Please address that tiny detail and request another review. Also, keep it in mind on subsequent projects because, generally I am to invalidate your PR and but seeing how much work you've put into this project, I didn't want to negatively impact your energy. Thanks for your patience!

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by Trodrige** [comment]
Hello, @Oluwadamilareolusakin Thank you for the remarks.

I just fixed all the issues and pushed. 

Please let me know.

**Review by addod19 — APPROVED** [review]
## Status: Approved :100: 
Hi @Trodrige  congratulations, you have done a great job meeting all the requirements and working on the changes required by the previous reviewer. :+1: 

Go ahead and merge to master. Don't forget to submit project completion form. :slightly_smiling_face:

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Comment by Trodrige** [comment]
Thank you @addod19

**Pull request merged**
